extends Node

var skill_data = {
	"Normal":{
		"Normal_SK1_Name":{
			"LV1":{"LV1":"Normal_SK1_Content_LV1"},
			"LV2":{"LV2":"Normal_SK1_Content_LV2"},
			"LV3":{"LV3":"Normal_SK1_Content_LV3"},
			"LV4":{"LV4":"Normal_SK1_Content_LV4"},
			"LV5":{"LV5":"Normal_SK1_Content_LV5"}		
		},
		"Normal_SK2_Name":{
			"LV1":{"LV1":"Normal_SK2_Content_LV1"},
			"LV2":{"LV2":"Normal_SK2_Content_LV2"},
			"LV3":{"LV3":"Normal_SK2_Content_LV3"},
			"LV4":{"LV4":"Normal_SK2_Content_LV4"},
			"LV5":{"LV5":"Normal_SK2_Content_LV5"}		
		},
		"Normal_SK3_Name":{
			"LV1":{"LV1":"Normal_SK3_Content_LV1"},
			"LV2":{"LV2":"Normal_SK3_Content_LV2"},
			"LV3":{"LV3":"Normal_SK3_Content_LV3"},
			"LV4":{"LV4":"Normal_SK3_Content_LV4"},
			"LV5":{"LV5":"Normal_SK3_Content_LV5"}		
		},
		"Normal_SK4_Name":{
			"LV1":{"LV1":"Normal_SK4_Content_LV1"},
			"LV2":{"LV2":"Normal_SK4_Content_LV2"},
			"LV3":{"LV3":"Normal_SK4_Content_LV3"},
			"LV4":{"LV4":"Normal_SK4_Content_LV4"},
			"LV5":{"LV5":"Normal_SK4_Content_LV5"}		
		},
		"Normal_SK5_Name":{
			"LV1":{"LV1":"Normal_SK5_Content_LV1"},
			"LV2":{"LV2":"Normal_SK5_Content_LV2"},
			"LV3":{"LV3":"Normal_SK5_Content_LV3"},
			"LV4":{"LV4":"Normal_SK5_Content_LV4"},
			"LV5":{"LV5":"Normal_SK5_Content_LV5"}		
		}
	},
	"Rare":{
		"Rare_SK1_Name":{
			"LV1":{"LV1":"Rare_SK1_Content_LV1"},
			"LV2":{"LV2":"Rare_SK1_Content_LV2"},
			"LV3":{"LV3":"Rare_SK1_Content_LV3"}
		},
		"Rare_SK2_Name":{
			"LV1":{"LV1":"Rare_SK2_Content_LV1"},
			"LV2":{"LV2":"Rare_SK2_Content_LV2"},
			"LV3":{"LV3":"Rare_SK2_Content_LV3"},
			"LV4":{"LV4A":"Rare_SK2_Content_LV4A",
			"LV4B":"Rare_SK2_Content_LV4B"},
			"LV5":{"LV5A":"Rare_SK2_Content_LV5A",
			"LV5B":"Rare_SK2_Content_LV5B"}
		},
		"Rare_SK3_Name":{
			"LV1":{"LV1":"Rare_SK3_Content_LV1"},
			"LV2":{"LV2":"Rare_SK3_Content_LV2"},
			"LV3":{"LV3A":"Rare_SK3_Content_LV3A","LV3B":"Rare_SK3_Content_LV3B"},
			"LV4":{"LV4A":"Rare_SK3_Content_LV4A","LV4B":"Rare_SK3_Content_LV4B"},
		}
	},
	"Legendary":{
		"Legendary_SK1_Name":{
			"LV1":{"LV1":"Legendary_SK1_Content_LV1"},
			"LV2":{"LV2":"Legendary_SK1_Content_LV2"},
			"LV3":{"LV3":"Legendary_SK1_Content_LV3"}
		},
		"Legendary_SK2_Name":{
			"LV1":{"LV1":"Legendary_SK2_Content_LV1"},
			"LV2":{"LV2":"Legendary_SK2_Content_LV2"},
			"LV3":{"LV3":"Legendary_SK2_Content_LV3"}
		},
		"Legendary_SK3_Name":{
			"LV1":{"LV1":"Legendary_SK3_Content_LV1"},
			"LV2":{"LV2":"Legendary_SK3_Content_LV2"},
			"LV3":{"LV3":"Legendary_SK3_Content_LV3"}
		},
		"Legendary_SK4_Name":{
			"LV1":{"LV1":"Legendary_SK4_Content_LV1"},
			"LV2":{"LV2":"Legendary_SK4_Content_LV2"},
			"LV3":{"LV3":"Legendary_SK4_Content_LV3"}
		}
	},
	"Empty":{
		"Empty":{
			"LV1":{"LV1":"111"},
			"LV2":{"LV2":"222"},
			"LV3":{"LV3":"333"}
		}
	}
}
